// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ArchiveActiveProject() {
  return window['go']['main']['App']['ArchiveActiveProject']();
}

export function CreateProject(arg1) {
  return window['go']['main']['App']['CreateProject'](arg1);
}

export function GetGatewayState() {
  return window['go']['main']['App']['GetGatewayState']();
}

export function GetProjectsOverview() {
  return window['go']['main']['App']['GetProjectsOverview']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function Health() {
  return window['go']['main']['App']['Health']();
}

export function OpenPath(arg1) {
  return window['go']['main']['App']['OpenPath'](arg1);
}

export function RestoreProject(arg1) {
  return window['go']['main']['App']['RestoreProject'](arg1);
}

export function SetGatewaySettings(arg1) {
  return window['go']['main']['App']['SetGatewaySettings'](arg1);
}

export function SetLastActiveView(arg1) {
  return window['go']['main']['App']['SetLastActiveView'](arg1);
}

export function SetThemePreference(arg1) {
  return window['go']['main']['App']['SetThemePreference'](arg1);
}

export function StartGateway() {
  return window['go']['main']['App']['StartGateway']();
}

export function StopGateway() {
  return window['go']['main']['App']['StopGateway']();
}
