// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {contracts} from '../models';

export function ArchiveActiveProject():Promise<void>;

export function CreateProject(arg1:contracts.CreateProjectInput):Promise<contracts.ProjectSummary>;

export function GetGatewayState():Promise<contracts.GatewayStateResponse>;

export function GetProjectsOverview():Promise<contracts.ProjectsOverview>;

export function GetSettings():Promise<contracts.Settings>;

export function Health():Promise<contracts.HealthResponse>;

export function OpenPath(arg1:contracts.OpenPathRequest):Promise<void>;

export function RestoreProject(arg1:contracts.RestoreProjectRequest):Promise<contracts.ProjectSummary>;

export function SetGatewaySettings(arg1:contracts.SetGatewaySettingsRequest):Promise<contracts.Settings>;

export function SetLastActiveView(arg1:contracts.AppView):Promise<contracts.Settings>;

export function SetThemePreference(arg1:contracts.ThemePreference):Promise<contracts.Settings>;

export function StartGateway():Promise<contracts.GatewayStateResponse>;

export function StopGateway():Promise<contracts.GatewayStateResponse>;
